name: ncvp
channels:
  - https://www.idiap.ch/software/bob/conda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2023.05.30=h06a4308_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.8=h7f8727e_0
  - pip=23.1.2=py39h06a4308_0
  - python=3.9.16=h955ad1f_3
  - readline=8.2=h5eee18b_0
  - setuptools=67.8.0=py39h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.38.4=py39h06a4308_0
  - xz=5.4.2=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - appdirs==1.4.4
      - asttokens==2.2.1
      - backcall==0.2.0
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - click==8.1.3
      - cmake==3.26.4
      - contourpy==1.1.0
      - cycler==0.11.0
      - decorator==5.1.1
      - docker-pycreds==0.4.0
      - executing==1.2.0
      - fastcore==1.5.29
      - filelock==3.12.2
      - fonttools==4.40.0
      - gitdb==4.0.10
      - gitpython==3.1.31
      - idna==3.4
      - importlib-resources==5.12.0
      - ipython==8.14.0
      - jedi==0.18.2
      - jinja2==3.1.2
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - lit==16.0.6
      - lovely-numpy==0.2.9
      - lovely-tensors==0.1.15
      - markupsafe==2.1.3
      - matplotlib==3.7.1
      - matplotlib-inline==0.1.6
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - networkx==3.1
      - numpy==1.25.0
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cuda-cupti-cu11==11.7.101
      - nvidia-cuda-nvrtc-cu11==11.7.99
      - nvidia-cuda-runtime-cu11==11.7.99
      - nvidia-cudnn-cu11==8.5.0.96
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.2.10.91
      - nvidia-cusolver-cu11==11.4.0.1
      - nvidia-cusparse-cu11==11.7.4.91
      - nvidia-nccl-cu11==2.14.3
      - nvidia-nvtx-cu11==11.7.91
      - packaging==23.1
      - pandas==2.0.2
      - parso==0.8.3
      - pathtools==0.1.2
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - prompt-toolkit==3.0.38
      - protobuf==4.23.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pygments==2.15.1
      - pyparsing==3.1.0
      - pyre-extensions==0.0.29
      - python-dateutil==2.8.2
      - pytorch-metric-learning==2.2.0
      - pytz==2023.3
      - pyyaml==6.0
      - requests==2.31.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - sentry-sdk==1.25.1
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - stack-data==0.6.2
      - sympy==1.12
      - threadpoolctl==3.1.0
      - torch==2.0.1
      - torchsummary==1.5.1
      - torchvision==0.15.2
      - tqdm==4.65.0
      - traitlets==5.9.0
      - triton==2.0.0
      - typing-extensions==4.6.3
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - urllib3==2.0.3
      - wandb==0.15.4
      - wcwidth==0.2.6
      - xformers==0.0.20
      - yacs==0.1.8
      - zipp==3.15.0
prefix: /home/bhartenduk/anaconda3/envs/ncvp
